//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manage_Furniture.Properties
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manage_Furniture.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        // Resources from both files combined
        internal static System.Drawing.Bitmap filter => ((System.Drawing.Bitmap)(ResourceManager.GetObject("filter", resourceCulture)));
        internal static System.Drawing.Bitmap filter__1_ => ((System.Drawing.Bitmap)(ResourceManager.GetObject("filter (1)", resourceCulture)));
        internal static System.Drawing.Bitmap IconSearch => ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconSearch", resourceCulture)));
        internal static System.Drawing.Bitmap _4e80d9de_5ed3_4ee7_8d66_5903f4dc7466 => ((System.Drawing.Bitmap)(ResourceManager.GetObject("4e80d9de-5ed3-4ee7-8d66-5903f4dc7466", resourceCulture)));
        internal static System.Drawing.Bitmap armchair_coffee => ((System.Drawing.Bitmap)(ResourceManager.GetObject("armchair coffee", resourceCulture)));
        internal static System.Drawing.Bitmap eye_1 => ((System.Drawing.Bitmap)(ResourceManager.GetObject("eye 1", resourceCulture)));
        internal static System.Drawing.Bitmap eye_off_2 => ((System.Drawing.Bitmap)(ResourceManager.GetObject("eye-off 2", resourceCulture)));
        internal static System.Drawing.Bitmap living => ((System.Drawing.Bitmap)(ResourceManager.GetObject("living", resourceCulture)));
        internal static System.Drawing.Bitmap log_in_1 => ((System.Drawing.Bitmap)(ResourceManager.GetObject("log-in 1", resourceCulture)));
        internal static System.Drawing.Bitmap logo1 => ((System.Drawing.Bitmap)(ResourceManager.GetObject("logo1", resourceCulture)));
        internal static System.Drawing.Bitmap search_1 => ((System.Drawing.Bitmap)(ResourceManager.GetObject("search 1", resourceCulture)));
    }
}
